export interface OrgStudent {
  id: string;
  name: string;
  email: string;
  quizCount: number;
  avgScore: number | null;
  flashcardCount: number;
  lastActive: string | null;
  status: "active" | "inactive" | "never";
}

export interface OrgDashboardMetrics {
  studentCount: number;
  seatLimit: number;
  activeStudents: number;
  quizzesTaken: number;
  flashcardSessions: number;
  avgScore: number;
  billingAmount: string;
  billingStatus: string;
  subscriptionStatus: "trialing" | "active" | "past_due" | "canceled" | "unpaid";
  trialDaysLeft: number | null;
}

export interface OrgStudentActivity {
  quizHistory: QuizHistoryEntry[];
  flashcardHistory: FlashcardHistoryEntry[];
}

export interface QuizHistoryEntry {
  id: string;
  fileTitle: string;
  score: number;
  date: string;
}

export interface FlashcardHistoryEntry {
  id: string;
  fileTitle: string;
  cardsReviewed: number;
  date: string;
}

export interface OrgFile {
  id: string;
  title: string;
  type: "pdf" | "text" | "youtube" | "image";
  uploadedAt: string;
  quizAttempts: number;
  flashcardSessions: number;
  summaryGenerated: boolean;
  visibleToStudents: boolean;
}

export interface GeneratedSet {
  id: string;
  type: "quiz" | "flashcards";
  title: string;
  questionCount: number;
  generatedAt: string;
}

export interface QuizQuestion {
  id: string;
  text: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface StudentFile {
  id: string;
  title: string;
  type: "pdf" | "youtube" | "text" | "image";
  uploadedBy: string;
  uploadedAt: string;
  quizCount: number;
  flashcardSetCount: number;
  summaryTitle?: string;
  summary?: string;
}

export interface StudentQuizAttempt {
  id: string;
  questionCount: number;
  score: number;
  date: string;
  time: string;
}

export interface StudentFlashcardSession {
  id: string;
  cardCount: number;
  date: string;
  reviewedAll: boolean;
}

export interface FlashCard {
  id: string;
  question: string;
  answer: string;
}

export interface QuizReviewItem {
  question: string;
  yourAnswer: string;
  correctAnswer: string;
  correct: boolean;
  explanation: string;
}

export interface StudentQuizResult {
  id: string;
  fileTitle: string;
  score: number;
  totalQuestions: number;
  correct: number;
  timeTakenMinutes: number;
  grade: string;
  date: string;
  reviewItems: QuizReviewItem[];
}

// ── Note detail (GET /notes/:noteId) ─────────────────────────────────────────

export interface NoteDetail {
  _id: string;
  title: string;
  /** HTML-formatted notes body generated by AI. */
  content?: string;
  /** Short plain-text summary generated by AI. */
  summary?: string;
  /**
   * Backend field name. The upload list uses the alias `type` below;
   * prefer `sourceType` when reading from the API directly.
   */
  sourceType?: 'pdf' | 'text' | 'youtube' | 'image' | 'audio';
  /** Legacy alias kept for FileCard / list compatibility. */
  type: 'pdf' | 'text' | 'youtube' | 'image';
  createdAt: string;
  updatedAt?: string;
  quizCount?: number;
  flashcardCount?: number;
  /** URL (or MinIO key) of the original uploaded file (PDF, image, audio). */
  sourceFileUrl?: string;
  /** Original filename as uploaded. */
  sourceFileName?: string;
  /** Raw text extracted before AI enhancement (useful as source fallback). */
  extractedContent?: string;
  /** Extra fields stored by the backend during ingestion. */
  metadata?: {
    youtubeVideoId?: string;
    youtubeTitle?: string;
    youtubeThumbnail?: string;
    originalFilename?: string;
    pages?: number;
  };
  processingStatus?: string;
}

// ── Admin-specific generate responses ────────────────────────────────────────
// These match the real backend shapes from POST /quizzes/generate and POST /flashcards/generate

export interface AdminQuizOption {
  id: string;
  text: string;
}

export interface AdminQuizQuestion {
  id: string;
  question: string;
  questionText?: string;
  questionType?: string;
  options: AdminQuizOption[];
  /** 0-based index (0–3) for multiple-choice, or letter string "A"–"D" */
  correctAnswer: number | string;
  explanation: string;
  difficulty?: string;
}

export interface AdminGeneratedQuiz {
  _id: string;
  title: string;
  questions: AdminQuizQuestion[];
  totalQuestions: number;
  noteId: string;
}

export interface AdminFlashcard {
  /** MongoDB subdocument _id — present when card comes from the API (FlashcardSet has _id:true). */
  _id?: string;
  front: string;
  back: string;
  color?: string;
}

export interface AdminGeneratedFlashcardSet {
  _id: string;
  title: string;
  cards: AdminFlashcard[];
  totalCards: number;
  noteId?: string;
}
